config/routes.rb
BlocBlog::Application.routes.draw do

  devise_for :users

  match 'about', :to => "home#about"

  resources :users

  resources :images

  resources :posts do
    resources :comments
   end 

 root :to => 'home#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
        if user.admin?
            can :manage, :all
        else
            can :read, :all
            can :create, Comment
            can :destroy, Comment
        end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :create_date, :delete_date, :post_id, :user_id

  default_scope order('created_at desc')
  
  belongs_to :user
  belongs_to :post
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
  attr_accessible :image_id, :url
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body, :author, :category

  validates :body,  presence: true
  validates :title, presence: true, uniqueness: true
  validates :category, presence: true

  default_scope order('created_at desc')
  
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :twitter, :website, :user_id

  has_many :posts
  has_many :comments

  validates :name, presence: true, uniqueness: true, length: { maximum: 30 } 
  validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private 

 rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, only: [ :create, :destroy ]

  def index
    @comments = @user.comments
  end

  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.build(params[:comment])
    @comment.user = current_user
      if @comment.save
        redirect_to @post, notice: 'Comment was successfully posted.'
      else
        render action: "create"
      end
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy

  	redirect_to @comment.post
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_filter :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy ]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
    @post.user = current_user

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
      authorize! :update, @post
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
    authorize! :update, @post
  end

  # POST /posts
  # POST /posts.json
  def create
    authorize! :create, @post
    @post = Post.new(params[:post])
    @post.user = current_user
      if @post.save
        redirect_to @post, notice: 'Post was successfully created.'
      else
        render action: "new"
      end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end

      authorize! :update, @post
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end

    authorize! :destroy, @post
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
    authorize! :update, @users
  end

  def new
  	@user = User.new
  end
  	
  def create
  	@user = User.new(params[:user])
  	if @user.save
		redirect_to @user
	else
		render :edit
	end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def show
  	@user = User.find(params[:id])
  end

  def update
	@user = User.find(params[:id])
	if @user.update_attributes(params[:user])
		redirect_to @user
	else
		render :edit
	end
  end

  def destroy
  	@user = User.find(params[:id])
	if @user.destroy
		redirect_to users_path
	else
		flash[:error] = "Error"
		redirect_to @user
	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/home/about.html.erb
<h1>About Me</h1>

<p>Dolore aliquam equidem pri ut, sit cu graeci principes, cu veritus suscipiantur nec. Ad mei causae cotidieque. At vis quot vidit delenit. Iriure pericula qui ex, ut quo essent scribentur referrentur.</p>

<p>Vel no facilis vivendo delicatissimi, ea inani saepe eum. Qui te iriure quaerendum, eu similique cotidieque sed. Ei persius graecis patrioque eum. Choro everti disputando duo ex, quod scripserit sit id. Saperet gubergren eam ut, verterem intellegebat no usu. Sea eu postea percipit, qui eu tincidunt theophrastus.</p>

<p>Quot rationibus per cu, cu usu reque nullam mediocrem. Idque eirmod dignissim te usu. Id sonet scaevola electram vis, eu modo semper omittam ius, cu legimus denique consetetur mei. In nam quod clita. Eum ex magna fugit, quo ea laudem salutandi deterruisset.</p>

<p>Partem repudiare sententiae ea pri, duo et oporteat assueverit. Ius an harum senserit, te quo scaevola democritum. Omittam delicatissimi mei eu, his velit persius aliquam ut, persius salutatus ius ei. Per tation aperiri disputationi et, dicant everti minimum sit ea. Diam paulo nihil pri te, vis suas aperiri sensibus eu. Vel omnes probatus in, ei tamquam omnesque vel. No nam magna qualisque forensibus, ex meis ancillae menandri eam.</p>

app/views/home/index.html.erb
<html>
  <header>
    <div class='hero-unit'>
      <h1>Jayne's Site</h1>
        <p>Welcome to my site. Learn more about me and see this sample blog here.</p>
          <p>
            <a class='btn btn-primary btn-large'>Read Posts</a>
          </p>  
    </div>
  </header>

<br/>
<br/>
<div class='row'>
  <div class='span3 offset2'><img src='http://placehold.it/400x400' class='img-circle' alt=''><h2>Sample Text</h2></div>
  <div class='span3 offset5'><img src='http://placehold.it/400x400' class='img-circle' alt=''><h2>Sample Text</h2></div>
</div>
<br/>
<br/>
  <p class='text-center'>
  <ul class='thumbnails'>
  <li class='span4'>
    <div class='thumbnail'>
      <img src="http://placehold.it/300x200" alt=''>
      <h3>Writing</h3>
      <p>See writing samples here...</p>
    </div>
  </li>
  <li class='span4'>
    <div class='thumbnail'>
      <img src="http://placehold.it/300x200" alt=''>
      <h3>Editing</h3>
      <p>See editing information here...</p>
     </div>
   </li>
   <li class='span4'>
    <div class='thumbnail'>
      <img src="http://placehold.it/300x200" alt=''>
      <h3>Writing</h3>
      <p>See writing samples here...</p>
    </div>
  </li>
  <li class='span4'>
    <div class='thumbnail'>
      <img src="http://placehold.it/300x200" alt=''>
      <h3>Writing</h3>
      <p>See writing samples here...</p>
    </div>
  </li>
  </ul>
  </p>

  
</html>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jayne Jang Belz</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">

</head>
<body style='padding:60px;'>
  <div class='navbar navbar-inverse navbar-fixed-top'>
    <div class='navbar-inner'>
    <div class = 'container'>
     <%= link_to 'Jayne Jang Belz', root_path, class: 'brand' %>
        <ul class='nav'>
          <li><%= link_to 'Home', root_url %></li> 
          <li><%= link_to 'Blog', posts_path %></li>
          <li><%= link_to 'About', about_path %></li>

          <% if can? :update, @post %>
          <li><%= link_to 'Users', users_path %></li>
          <% end %>

          <% if current_user %>
            <li><%= link_to current_user.name %></li>
            <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Sign Out', destroy_user_session_path %></li>
          <% else %>
            <li><%= link_to 'Register', new_user_registration_path %></li>
            <li><%= link_to 'Sign In', new_user_session_path %></li>
          <% end %>  
        </ul>  
    </div>
    </div>
  </div>
            
<%= yield %>

</body>
</html>

app/views/posts/_comment.html.erb
  <div id='comments'>
    <h2><i class='icon-comment'></i> Comments</h2>
      <% @post.comments.each do |c| %>
    
      <div id = 'individual_comment'>
        <p><%= c.body %></p>
        <p style = 'font-size: 80%;'><em>Posted by <%= c.user.name %> <%= time_ago_in_words(c.created_at) %> ago</em></p>
      </div>  
      <% end %>
  
    <%= form_for [@post, @post.comments.build] do |f| %>
    <h4><em><strong><%= f.label :body, "Insert new comment" %></strong></em></h4>
    <p><%= f.text_area :body, :size => "550x6" %>
    <p><%= f.submit "Submit" %>
  <% end %>  
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id='error_explanation'>
      <h2><%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class='field'>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class='field'>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class='field'>
    <%= f.label :category %>
    <%= f.text_field :category %>
  </div>
  <div class='field'>
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
   
  <div class='actions'>
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  </head>


<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

</html>

app/views/posts/index.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  </head>

  <div class='row-fluid'>
  <div class='span11 offset1'>

    <p><img src='http://placehold.it/1750x300'/></p>

      <div class='span8'>
      <div class='well'>  
        
        <% @posts.each do |post| %>
        <!-- Admin tools -->
        <section id='post'> 
          <% if can? :update, @post %>
          <div class='btn-toolbar pull-right'>
          <div class='btn-group'>
            <button class='btn'><i class="icon-edit"></i> <%= link_to 'Edit', edit_post_path(post) %></button>
            <button class='btn'><i class="icon-trash"></i> <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></button>
          </div>
          </div>  
          <% end %>

        <h2 class='post-title'><%= link_to post.title, post %></h2>
        <p class='post-date'><em>Posted by</em> <%= post.user.name %> <em><%= time_ago_in_words(post.created_at) %> ago</em> in <%= post.category %> </p>
        <p class='post-text'><%= post.body %></p>
        </section>
        <% end %>

      </div>
      </div>

      <div class='span3'>
      <div class='well'> 
        <img src='http://placehold.it/400x400' class='img-rounded' alt=''>

        <h3>Recent Posts</h3>
          <% @posts.each do |post| %>
          <p><%= link_to post.title, post %></p>
          <% end %>

        <h3>Recent Comments</h3>
          <p>Hello</p>

        <% if can? :update, @post %>    
        <div class='btn-group'>
          <button class='btn btn-large'><i class="icon-pencil"></i> <%= link_to 'Create New Post', new_post_path %></button>
          <br/>
        </div>
        <% end %>
    
      </div>
      </div>

  </div>
</div>

</html>

app/views/posts/new.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  </head>
  
<h1>Create New Post</h1>

<p>
  <%= form_for @post do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, autocomplete: 'off', size: "30x10", placeholder: 'Title your post here...' %>
  <br>

  <%= f.label :body %>
  <%= f.text_area :body, autocomplete: 'off', size: "30x10", placeholder: 'Start writing your post here...' %>
  <br> 

  <%= f.label :category %>
  <%= f.text_field :category, size: "30x10", placeholder: 'Select from Food, Travel' %>
  <br>

  <%= f.label :author %>
  <%= f.text_field :author, size: "30x10", placeholder: 'Written by...' %>
  <br>

  <%= f.submit "Create Post" %>
  <% end %>
</p>

</html>

app/views/posts/show.html.erb
<html>
<p id="notice"><%= notice %></p>

<div class='row-fluid'>
<div class='span11 offset1'>
    <p><img src='http://placehold.it/1750x300'/></p>

    <h3><i class='icon-arrow-left'></i> <em><%= link_to "Return to all posts", posts_path %></em></h3>

    <div class='span8'>
    <div class='well'>  
      <section id='post'>
        <h2 class='post-title'><%= @post.title %></h2>
          <p class='post-date'><em>Posted by</em> <%= @post.user.name %> <em><%= time_ago_in_words(@post.created_at) %> ago</em> in <%= @post.category %> </p>
          <p class='post-text'><%= @post.body %></p>
    </div>
    </div>  

    <div class='span3'>
    <div class='well'> 
      <div class='btn-group'>
        <button class='btn btn-large'><i class="icon-pencil"></i> <%= link_to 'Create New Post', new_post_path %></button>
      </div>

      <h3>Recent Posts</h3>
        <p>Hello</p>
      <h3>Recent Comments</h3>
        <p>Hello</p>    
    </div>
    </div>

</div>
</div>

</section>

  <div class='row'>
  <div class='span8 offset3'>
  <div class='well'>

    <%= render 'comment' %>

  </div>
  </div>
  </div>

<h4>Admin:</h4>
  <p>
    <div class='btn-toolbar'>
    <div class='btn-group'>
      <button class='btn'><i class="icon-edit"></i> <%= link_to 'Edit', edit_post_path(@post) %></button>
      <button class='btn'><i class="icon-arrow-left"></i> <%= link_to 'Back', posts_path %></button>
      <button class='btn'><i class="icon-trash"></i> <%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %></button>
    </div>
    </div>  
  </p>


</html>

app/views/users/create.html.erb
<html>
	<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  </head>

<h1>Create a user profile</h1>

<p>
	<%= form_for @user do |f| %>
	<br>
	<%= f.label :name, "Username" %>
	<br>
	<%= f.text_field :name %>

	<%= f.label :bio, "Short Bio" %>
	<br>
	<%= f.text_field :bio %>

	<%= f.label :email, "Email Address" %>
	<br>
	<%= f.text_field :email %>

	<%= f.label :twitter, "Twitter" %>
	<br>
	<%= f.text_field :twitter %>

	<%= f.label :website, "Website" %>
	<br>
	<%= f.text_field :website %>

	<%= f.submit "Submit" %>
</p>
<% end %>

</html>

app/views/users/edit.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  </head>

<h1>Update your user profile</h1>
<br>
<%= render 'form' %>

app/views/users/index.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  </head>

<h1>Listing Users</h1>

<table class='table table-striped'>
  <tr>
    <th>Name</th>
    <th>Email</th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<div class='btn-group pull-left'>
    <button class='btn btn-large'><%= link_to 'Sign up to create a user profile', new_user_registration_path %></button>
</div>

</html>

app/views/users/new.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  </head>

<h1>Create a User Profile</h1>
<br/>
  <%= render 'form' %>

<br/>

<div class='btn-group pull-left'>
    <button class='btn btn-large'><%=link_to 'Return to all users', users_path %></button>
</div>


</html>

app/views/users/show.html.erb
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  </head>

<h1><i class="icon-user"></i> User Profile</h1>
<p><%=link_to 'Return to all users', users_path %></p>
<hr />
<h2>Basic Info</h2>
<p><strong>Name:</strong> <%= @user.name %></p>
<p><strong>Email:</strong> <%= @user.email %></p>
<p><strong>Twitter:</strong> <%= @user.twitter %></p>
<p><strong>Website:</strong> <%= @user.website %></p>

<hr />
<h2>Posts by <%= @user.name %></h2>
<% @user.posts.each do |post| %>
    <p><%= link_to post.title, post_path(post) %></p>

<hr />


<% end %>

</html>